brainstormforce/bb-bootstrap-alerts

bb-bootstrap-alerts.php
Added admin notice message when Beaver Builder is not Activated/Installed
See #5
=> added admin notice when bb not installed/activated

readme.txt
Updated contents of Readme.txt file
See #3
=> edited readme file

bb-bootstrap-alerts.php
Loaded text domain plugin.
See #1
=> loaded text domain plugin

readme.md, readme.txt
Added Beaver builder required instruction and link of Beaver Builder
=> Added BB Link

bb-bootstrap-alerts-module/bb-bootstrap-alerts-module.php, bb-bootstrap-alerts-module/css/frontend.css, bb-bootstrap-alerts-module/includes/frontend.css.php, bb-bootstrap-alerts-module/includes/frontend.php, bb-bootstrap-alerts.php
Replaced text domain in the main file.
=> Replaced remaining text domain

bb-bootstrap-alerts-module/bb-bootstrap-alerts-module.php, bb-bootstrap-alerts-module/css/frontend.css, bb-bootstrap-alerts-module/includes/frontend.css.php, bb-bootstrap-alerts-module/includes/frontend.js.php, bb-bootstrap-alerts-module/includes/frontend.php, bb-bootstrap-alerts-module/js/frontend.js, bb-bootstrap-alerts-module/js/js_cookie.js, bb-bootstrap-alerts.php, readme.txt
Cookie based notification added.
=> feature added cookie based notification

bb-bootstrap-alerts-module/bb-bootstrap-alerts-module.php, bb-bootstrap-alerts.php, readme.txt
=> Version bump V1.1.0

bb-bootstrap-alerts-module/includes/frontend.css.php
- Fixed PHP illegal warnings and notices for font family and font weight of the text
=> Fixed PHP illegal warnings and notices for font family and font weight

bb-bootstrap-alerts.php, readme.txt
- Fix: PHP illegal warnings and notices for font family and font-weight
=> Update plugin to v1.2.1

readme.txt
- Updated Tested Upto tag in readme file
=> Updated Tested Upto tag in readme file

readme.txt
Test WordPress 5.5 compatibility
=> Test WordPress 5.5 compatibility

bb-bootstrap-alerts-module/js/bootstrap_alerts.js, readme.txt
- Updated Bootstrap Alert JS for compatibility with latest JQuery in WP 5.6
Screenshot - https://share.getcloudapp.com/DOuoqqb6
Reference - https://getbootstrap.com/docs/4.0/components/alerts/
=> WordPress 5.6 Compatibility

readme.txt
WordPress 5.7 update compatibility
=> WordPress 5.7 update compatibility

bb-bootstrap-alerts-module/includes/frontend.css.php, bb-bootstrap-alerts.php, readme.txt
###Description
PHP Notice:  Undefined index: weight due to updated php version
=> Fix: Compatibility improvement - PHP Notice

readme.txt
No issues were found
Updated tested up to tag to 6.0
=> WordPress 6.0 compatibility

bb-bootstrap-alerts.php, readme.txt
- Improvement: Added compatibility to WordPress 6.1
- Updated contributor name
=> Updated Tested Upto tag and Contributor name

readme.txt
No issues were found
Updated Tested up to tag to 6.2
=> WordPress 6.2 compatibility

readme.txt
=> WordPress 6.3 compatibility

readme.txt
No issues found
Updated tested upto tag
=> WordPress 6.4 compatibility

readme.txt
=> EPS-460: Wordpress 6.5 testing 

bb-bootstrap-alerts-module/includes/frontend.php, bb-bootstrap-alerts.php, readme.txt
=> EPS-612: Improved codebase
